#!/usr/bin/env bash
#function for outputting, badluck, goodluck and best school

COUNTER=0
while [ $COUNTER -lt 10 ]
do
	if [ $COUNTER = 3 ]
	then
		echo "bad luck"
	elif [ $COUNTER = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( COUNTER++ ))
done
