#!/usr/bin/env bash
#script that configures localhost and facebook servers
sudo cp /etc/hosts/ ~/hosts.old
sed -i s/.*127.0.0.1/127.0.0.2 127.0.0.1/g ~/hosts.old
sed -i s/.*facebook.com//g ~/hosts.old
sed -i 1 a 8.8.8.8 facebook.com ~/hosts.old
sudo cp -f ~/hosts.old /etc/hosts
